--- #YAML:1.0
name:                Net-TacacsPlus
version:             1.08
abstract:            Tacacs+ library
license:             perl
author:              
    - Jozef Kutej <jkutej@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp::Clan:                    0
    Class::Accessor::Fast:         0
    Digest::MD5:                   0
    IO::Socket:                    0
    Log::Log4perl:                 0
    Math::XOR:                     0
    POE:                           0
    Test::Differences:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
